use_frameworks!
platform :ios, '11.0'


# Import CocoaPods sources
source 'https://github.com/CocoaPods/Specs.git'

target 'EaseIM' do

    pod 'MBProgressHUD'
    pod 'Masonry'
    pod 'MJRefresh'
    pod 'HyphenateChat'
    pod 'SDWebImage', '~> 3.7.2'
    pod 'AgoraRtcEngine_iOS'
    pod 'EaseCallKit'
end

