use_frameworks!
platform :ios, '11.0'


# Import CocoaPods sources
source 'https://github.com/CocoaPods/Specs.git'

target 'EaseIM' do

    pod 'MBProgressHUD'
    pod 'Masonry'
    pod 'MJRefresh'
    pod 'Hyphenate'
    pod 'EaseIMKit'
    
end

