use_frameworks!
platform :ios, '11.0'


# Import CocoaPods sources
source 'https://github.com/CocoaPods/Specs.git'

target 'EaseIM' do

    pod 'MBProgressHUD'
    pod 'Masonry'
    pod 'MJRefresh'
    pod 'SDWebImage'
    pod 'AgoraRtcEngine_iOS','3.6.1.2'
    pod 'FMDB'
    pod 'HyphenateChat'
    pod 'EaseIMKit'
    pod 'EaseCallKit'

    #pod 'EaseCallKit',  :path => "../../EaseCallKit/easecallkitui-ios"
    #pod 'EaseIMKit',  :path => "../../EaseIMKit_Release"

    pod 'Bugly'
    pod 'EMTranslate'
    
end

