# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'EaseChatDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EaseChatDemo
  pod 'EaseChatUIKit'
  pod 'EaseCallKit'
  pod 'KakaJSON', '~> 1.1.2'
  pod 'SwiftFFDBHotFix'
  pod 'FMDB','2.7.11'
  post_install do |installer|
    installer.generated_projects.each do |project|
      
      project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "13.0"
          config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
          config.build_settings["DEVELOPMENT_TEAM"] = "JC854K845H"
        end
      end
    end
  end
end
